name: analytical_platform

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: retail_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0.0.0.0:5430:5432"
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
      - ./postgres/backups:/backups
      - ./postgres/wal:/backup/wal
      - ./postgres/pglogs:/var/log/postgresql
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf
      -c max_connections=1000
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - retail_network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: olap_retail
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-init:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - retail_network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "0.0.0.0:4566:4566"
      - "0.0.0.0:4510-4559:4510-4559"
      - "0.0.0.0:8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/data
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - EXTRA_CORS_ALLOWED_ORIGINS=*
    volumes:
      - ./.localstack_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - retail_network

  superset:
    image: apache/superset:4.0.1
    container_name: superset
    ports:
      - "0.0.0.0:8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_DATABASE_URI: "postgresql+psycopg2://${SUPERSET_POSTGRES_USER}:${SUPERSET_POSTGRES_PASSWORD}@supersetdb:5432/${SUPERSET_POSTGRES_DB}"
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      PYTHONPATH: /app/pythonpath
    volumes:
      - ./superset_home:/app/superset_home
      - ./docker/requirements-local.txt:/app/requirements-local.txt
      - ./superset-custom/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset-custom/templates/appbuilder:/usr/local/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder:rw
      - ./superset-custom/templates/superset:/app/superset/templates/superset:ro
      - ./superset-custom/static:/app/superset/static/custom:rw
      - ./superset-custom/assets:/app/superset/static/assets/local:rw
    networks:
      - retail_network
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  supersetdb:
    image: postgres:16
    container_name: supersetdb
    environment:
      POSTGRES_USER: ${SUPERSET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SUPERSET_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SUPERSET_POSTGRES_DB}
    volumes:
      - ./supersetdb_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5431:5432"
    networks:
      - retail_network
    restart: unless-stopped


networks:
  retail_network:
    driver: bridge

volumes:
  clickhouse_data:
  clickhouse_logs:
