INSERT INTO sales.delivery_types (code, name, description, active) VALUES
('store_pickup', 'Store Pickup', 'Customer picks up order from store location', true),
('courier_standard', 'Courier Standard', 'Standard courier delivery within 3-5 business days', true),
('courier_express', 'Courier Express', 'Express courier delivery within 1-2 business days', true),
('courier_same_day', 'Same Day Delivery', 'Courier delivery on the same day if ordered before cutoff time', true),
('courier_next_day', 'Next Day Delivery', 'Guaranteed delivery next business day', true),
('courier_scheduled', 'Scheduled Delivery', 'Delivery scheduled for specific date and time slot', true),
('courier_evening', 'Evening Delivery', 'Delivery during evening hours 18:00-22:00', true),
('courier_weekend', 'Weekend Delivery', 'Delivery on Saturday or Sunday', true),
('pickup_point', 'Pickup Point', 'Customer collects order from pickup point or parcel locker', true),
('post_standard', 'Post Standard', 'Standard postal service delivery', true),
('post_registered', 'Registered Post', 'Registered mail with tracking', true),
('post_express', 'Express Post', 'Express postal service', true),
('parcel_locker', 'Parcel Locker', 'Automated parcel locker self-service pickup', false),
('click_and_collect', 'Click & Collect', 'Order online, collect from store within hours', true),
('drive_through', 'Drive Through', 'Curbside pickup without leaving vehicle', true),
('in_store', 'In Store', 'Purchase and take immediately from store', true),
('home_delivery', 'Home Delivery', 'Delivery directly to customer home address', true),
('office_delivery', 'Office Delivery', 'Delivery to office or business address', true),
('contactless', 'Contactless Delivery', 'No-contact delivery, leave at door', true),
('white_glove', 'White Glove Delivery', 'Premium delivery with unpacking and setup', true),
('furniture_delivery', 'Furniture Delivery', 'Specialized delivery for furniture and large items', true),
('appliance_delivery', 'Appliance Delivery', 'Delivery and installation of appliances', true),
('heavy_cargo', 'Heavy Cargo', 'Delivery of heavy or oversized items', true),
('assembly_included', 'Assembly Included', 'Delivery with product assembly service', true),
('install_included', 'Installation Included', 'Delivery with installation service', true),
('two_person_delivery', 'Two Person Delivery', 'Delivery requiring two delivery personnel', true),
('room_of_choice', 'Room of Choice', 'Delivery to specific room in customer home', true),
('freight', 'Freight Shipping', 'Freight carrier for large or bulk orders', true),
('ltl_freight', 'LTL Freight', 'Less than truckload freight shipping', true),
('ftl_freight', 'FTL Freight', 'Full truckload freight shipping', true),
('international', 'International Delivery', 'Cross-border international shipping', true),
('international_express', 'International Express', 'Express international shipping', true),
('international_economy', 'International Economy', 'Economy international shipping', true),
('dhl_express', 'DHL Express', 'DHL express international delivery', true),
('fedex_express', 'FedEx Express', 'FedEx express delivery service', true),
('ups_express', 'UPS Express', 'UPS express delivery service', true),
('local_courier', 'Local Courier', 'Local courier service within city', true),
('bike_courier', 'Bike Courier', 'Bicycle courier for quick urban delivery', true),
('motorcycle_courier', 'Motorcycle Courier', 'Motorcycle courier for fast city delivery', true),
('drone_delivery', 'Drone Delivery', 'Automated drone delivery (pilot program)', true),
('robot_delivery', 'Robot Delivery', 'Autonomous robot delivery', true),
('subscription_delivery', 'Subscription Delivery', 'Regular scheduled delivery for subscriptions', true),
('auto_delivery', 'Auto Delivery', 'Automatic recurring delivery', true),
('marketplace_delivery', 'Marketplace Delivery', 'Delivery via marketplace logistics partner', true),
('third_party_logistics', '3PL Delivery', 'Third-party logistics provider delivery', true),
('drop_shipping', 'Drop Shipping', 'Direct shipping from supplier to customer', true),
('direct_from_warehouse', 'Direct from Warehouse', 'Shipped directly from distribution center', true),
('cross_dock', 'Cross Dock', 'Cross-docking delivery without warehousing', true),
('consolidation', 'Consolidation Delivery', 'Multiple orders consolidated into one delivery', true),
('split_delivery', 'Split Delivery', 'Order delivered in multiple shipments', true),
('partial_delivery', 'Partial Delivery', 'Partial order delivery, rest to follow', true),
('backorder_delivery', 'Backorder Delivery', 'Delivery of backordered items separately', true),
('gift_delivery', 'Gift Delivery', 'Special gift wrapping and delivery service', true),
('gift_message', 'Gift with Message', 'Delivery with personalized gift message', true),
('cold_chain', 'Cold Chain Delivery', 'Temperature-controlled delivery for perishables', true),
('frozen_delivery', 'Frozen Delivery', 'Delivery maintaining frozen temperature', true),
('refrigerated', 'Refrigerated Delivery', 'Refrigerated transport for fresh goods', true),
('pharmacy_delivery', 'Pharmacy Delivery', 'Specialized delivery for pharmaceutical products', true),
('medical_courier', 'Medical Courier', 'Medical-grade courier for sensitive items', true),
('alcohol_delivery', 'Alcohol Delivery', 'Age-verified delivery for alcoholic beverages', false),
('signature_required', 'Signature Required', 'Delivery requiring recipient signature', true),
('id_verification', 'ID Verification', 'Delivery with mandatory ID check', true),
('age_verification', 'Age Verification', 'Delivery with age verification (18+/21+)', true),
('secure_delivery', 'Secure Delivery', 'High-security delivery for valuable items', true),
('insured_delivery', 'Insured Delivery', 'Delivery with insurance coverage', true),
('track_and_trace', 'Track & Trace', 'Real-time tracking enabled delivery', true),
('sms_notification', 'SMS Notification', 'Delivery with SMS updates', true),
('photo_confirmation', 'Photo Confirmation', 'Delivery with photo proof', true),
('gps_tracked', 'GPS Tracked', 'Live GPS tracking of delivery', true),
('eco_delivery', 'Eco Delivery', 'Environmentally friendly electric vehicle delivery', true),
('carbon_neutral', 'Carbon Neutral', 'Carbon-offset delivery service', true),
('bicycle_delivery', 'Bicycle Delivery', 'Eco-friendly bicycle delivery', true),
('electric_vehicle', 'Electric Vehicle', 'Delivery using electric vehicles', true),
('economy', 'Economy Delivery', 'Low-cost economy shipping option', true),
('free_delivery', 'Free Delivery', 'Free shipping promotion', true),
('free_over_amount', 'Free Over Amount', 'Free delivery for orders over threshold', true),
('flat_rate', 'Flat Rate', 'Fixed flat rate delivery fee', true),
('calculated_rate', 'Calculated Rate', 'Delivery fee calculated by weight/distance', true),
('rush_delivery', 'Rush Delivery', 'Urgent rush delivery service', true),
('overnight', 'Overnight Delivery', 'Guaranteed overnight delivery', true),
('two_hour', 'Two Hour Delivery', 'Ultra-fast 2-hour delivery window', true),
('one_hour', 'One Hour Delivery', 'Premium 1-hour delivery service', true),
('instant_delivery', 'Instant Delivery', 'On-demand instant delivery (15-30 min)', true),
('hyperlocal', 'Hyperlocal Delivery', 'Local neighborhood delivery service', true),
('locker_network', 'Locker Network', 'Delivery to network of automated lockers', false),
('collection_point', 'Collection Point', 'Delivery to partner collection point', true),
('post_office_pickup', 'Post Office Pickup', 'Collection from post office', true),
('gas_station_pickup', 'Gas Station Pickup', 'Pickup from gas station partner', true),
('retail_partner_pickup', 'Retail Partner Pickup', 'Pickup from retail partner location', true),
('subway_locker', 'Subway Locker', 'Parcel locker in subway station', true),
('train_station_pickup', 'Train Station Pickup', 'Pickup from train station', true),
('airport_pickup', 'Airport Pickup', 'Pickup from airport location', true),
('shopping_mall_pickup', 'Shopping Mall Pickup', 'Pickup from shopping mall locker', true),
('university_pickup', 'University Pickup', 'Campus pickup point for students', true),
('workplace_delivery', 'Workplace Delivery', 'Delivery to workplace reception', true),
('concierge_delivery', 'Concierge Delivery', 'Delivery to building concierge', true),
('neighbor_delivery', 'Neighbor Delivery', 'Delivery to neighbor if customer absent', false),
('safe_place', 'Safe Place Delivery', 'Leave in designated safe place', true),
('garage_delivery', 'Garage Delivery', 'Delivery to garage or storage area', false),
('trunk_delivery', 'Trunk Delivery', 'Delivery to car trunk (Amazon Key)', true),
('try_before_buy', 'Try Before Buy', 'Try items at home, return unwanted', true),
('return_pickup', 'Return Pickup', 'Pickup service for returns', true),
('exchange_delivery', 'Exchange Delivery', 'Simultaneous exchange during delivery', true),
('unattended_delivery', 'Unattended Delivery', 'Leave package unattended as instructed', true),
('attended_delivery', 'Attended Delivery', 'Hand to recipient only', true),
('business_delivery', 'Business Delivery', 'Delivery during business hours only', true),
('residential_delivery', 'Residential Delivery', 'Residential address delivery', true),
('rural_delivery', 'Rural Delivery', 'Delivery to rural or remote areas', true),
('island_delivery', 'Island Delivery', 'Delivery to islands or remote locations', false),
('military_base', 'Military Base', 'Delivery to military APO/FPO addresses', true),
('po_box', 'PO Box', 'Delivery to post office box', true);