INSERT INTO sales.payment_methods (code, name, description, active, meta) VALUES

('cash', 'Наличные', 'Оплата наличными деньгами при получении', true, '{"icon": "cash", "fee": 0, "processing_time": "instant"}'),
('card', 'Банковская карта', 'Оплата банковской картой', true, '{"icon": "credit-card", "fee": 2.5, "processing_time": "instant", "types": ["visa", "mastercard", "mir"]}'),
('debit_card', 'Дебетовая карта', 'Оплата дебетовой картой', true, '{"icon": "card", "fee": 2.0, "processing_time": "instant"}'),
('credit_card', 'Кредитная карта', 'Оплата кредитной картой', true, '{"icon": "card", "fee": 3.0, "processing_time": "instant"}'),

('bank_transfer', 'Банковский перевод', 'Перевод на расчетный счет', true, '{"icon": "bank", "fee": 1.0, "processing_time": "1-3 days"}'),
('wire_transfer', 'Wire Transfer', 'Международный банковский перевод', true, '{"icon": "bank", "fee": 5.0, "processing_time": "3-5 days"}'),
('sepa', 'SEPA', 'Перевод в европейской зоне SEPA', true, '{"icon": "bank", "fee": 1.5, "processing_time": "1-2 days", "region": "EU"}'),
('swift', 'SWIFT', 'Международный перевод SWIFT', true, '{"icon": "bank", "fee": 7.0, "processing_time": "3-7 days"}'),
('sbp', 'СБП', 'Система быстрых платежей', true, '{"icon": "fast-payment", "fee": 0, "processing_time": "instant", "region": "RU"}'),
('fps', 'FPS', 'Faster Payment Service (UK)', true, '{"icon": "fast-payment", "fee": 0, "processing_time": "instant", "region": "UK"}'),

('paypal', 'PayPal', 'Оплата через PayPal', true, '{"icon": "paypal", "fee": 3.4, "processing_time": "instant", "currency": ["USD", "EUR", "GBP"]}'),
('qiwi', 'QIWI', 'Оплата через QIWI кошелек', true, '{"icon": "qiwi", "fee": 2.0, "processing_time": "instant", "region": "RU"}'),
('yoomoney', 'ЮMoney', 'Оплата через ЮMoney (Яндекс.Деньги)', true, '{"icon": "yoomoney", "fee": 2.0, "processing_time": "instant", "region": "RU"}'),
('webmoney', 'WebMoney', 'Оплата через WebMoney', true, '{"icon": "webmoney", "fee": 2.5, "processing_time": "instant"}'),
('skrill', 'Skrill', 'Оплата через Skrill', true, '{"icon": "skrill", "fee": 2.9, "processing_time": "instant"}'),
('neteller', 'Neteller', 'Оплата через Neteller', true, '{"icon": "neteller", "fee": 2.5, "processing_time": "instant"}'),
('payoneer', 'Payoneer', 'Оплата через Payoneer', true, '{"icon": "payoneer", "fee": 3.0, "processing_time": "instant"}'),
('stripe', 'Stripe', 'Оплата через Stripe', true, '{"icon": "stripe", "fee": 2.9, "processing_time": "instant"}'),
('square', 'Square', 'Оплата через Square', true, '{"icon": "square", "fee": 2.6, "processing_time": "instant"}'),
('venmo', 'Venmo', 'Оплата через Venmo', true, '{"icon": "venmo", "fee": 3.0, "processing_time": "instant", "region": "US"}'),
('zelle', 'Zelle', 'Оплата через Zelle', true, '{"icon": "zelle", "fee": 0, "processing_time": "instant", "region": "US"}'),
('cashapp', 'Cash App', 'Оплата через Cash App', true, '{"icon": "cashapp", "fee": 2.75, "processing_time": "instant", "region": "US"}'),

('apple_pay', 'Apple Pay', 'Оплата через Apple Pay', true, '{"icon": "apple", "fee": 2.5, "processing_time": "instant", "devices": ["iPhone", "iPad", "Mac"]}'),
('google_pay', 'Google Pay', 'Оплата через Google Pay', true, '{"icon": "google", "fee": 2.5, "processing_time": "instant", "devices": ["Android"]}'),
('samsung_pay', 'Samsung Pay', 'Оплата через Samsung Pay', true, '{"icon": "samsung", "fee": 2.5, "processing_time": "instant", "devices": ["Samsung"]}'),
('alipay', 'Alipay', 'Оплата через Alipay', true, '{"icon": "alipay", "fee": 2.0, "processing_time": "instant", "region": "CN"}'),
('wechat_pay', 'WeChat Pay', 'Оплата через WeChat Pay', true, '{"icon": "wechat", "fee": 2.0, "processing_time": "instant", "region": "CN"}'),
('paytm', 'Paytm', 'Оплата через Paytm', true, '{"icon": "paytm", "fee": 2.0, "processing_time": "instant", "region": "IN"}'),
('phonepe', 'PhonePe', 'Оплата через PhonePe', true, '{"icon": "phonepe", "fee": 1.5, "processing_time": "instant", "region": "IN"}'),
('gpay_india', 'Google Pay India', 'Google Pay для Индии', true, '{"icon": "google", "fee": 0, "processing_time": "instant", "region": "IN"}'),

('bitcoin', 'Bitcoin (BTC)', 'Оплата в Bitcoin', true, '{"icon": "bitcoin", "fee": 1.0, "processing_time": "10-60 min", "blockchain": "Bitcoin"}'),
('ethereum', 'Ethereum (ETH)', 'Оплата в Ethereum', true, '{"icon": "ethereum", "fee": 2.0, "processing_time": "1-5 min", "blockchain": "Ethereum"}'),
('usdt', 'Tether (USDT)', 'Оплата в Tether', true, '{"icon": "tether", "fee": 1.0, "processing_time": "5-10 min", "stablecoin": true}'),
('usdc', 'USD Coin (USDC)', 'Оплата в USD Coin', true, '{"icon": "usdc", "fee": 1.0, "processing_time": "5-10 min", "stablecoin": true}'),
('litecoin', 'Litecoin (LTC)', 'Оплата в Litecoin', true, '{"icon": "litecoin", "fee": 0.5, "processing_time": "2-5 min", "blockchain": "Litecoin"}'),
('ripple', 'Ripple (XRP)', 'Оплата в Ripple', true, '{"icon": "ripple", "fee": 0.3, "processing_time": "3-5 sec", "blockchain": "XRP Ledger"}'),
('cardano', 'Cardano (ADA)', 'Оплата в Cardano', true, '{"icon": "cardano", "fee": 0.5, "processing_time": "5-10 min", "blockchain": "Cardano"}'),
('solana', 'Solana (SOL)', 'Оплата в Solana', true, '{"icon": "solana", "fee": 0.1, "processing_time": "1-2 sec", "blockchain": "Solana"}'),
('bnb', 'Binance Coin (BNB)', 'Оплата в Binance Coin', true, '{"icon": "binance", "fee": 0.5, "processing_time": "1-3 min", "blockchain": "BSC"}'),
('polygon', 'Polygon (MATIC)', 'Оплата в Polygon', true, '{"icon": "polygon", "fee": 0.2, "processing_time": "1-2 min", "blockchain": "Polygon"}'),
('dogecoin', 'Dogecoin (DOGE)', 'Оплата в Dogecoin', true, '{"icon": "dogecoin", "fee": 0.3, "processing_time": "1-3 min", "blockchain": "Dogecoin"}'),
('ton', 'TON Coin', 'Оплата в TON', true, '{"icon": "ton", "fee": 0.1, "processing_time": "5 sec", "blockchain": "TON"}'),

('ideal', 'iDEAL', 'Нидерландская платежная система', true, '{"icon": "ideal", "fee": 1.5, "processing_time": "instant", "region": "NL"}'),
('giropay', 'Giropay', 'Немецкая платежная система', true, '{"icon": "giropay", "fee": 1.5, "processing_time": "instant", "region": "DE"}'),
('sofort', 'Sofort', 'Европейская платежная система', true, '{"icon": "sofort", "fee": 2.0, "processing_time": "instant", "region": "EU"}'),
('bancontact', 'Bancontact', 'Бельгийская платежная система', true, '{"icon": "bancontact", "fee": 1.5, "processing_time": "instant", "region": "BE"}'),
('eps', 'EPS', 'Австрийская платежная система', true, '{"icon": "eps", "fee": 1.5, "processing_time": "instant", "region": "AT"}'),
('przelewy24', 'Przelewy24', 'Польская платежная система', true, '{"icon": "p24", "fee": 2.0, "processing_time": "instant", "region": "PL"}'),
('multibanco', 'Multibanco', 'Португальская платежная система', true, '{"icon": "multibanco", "fee": 1.5, "processing_time": "instant", "region": "PT"}'),
('mercadopago', 'Mercado Pago', 'Латиноамериканская платежная система', true, '{"icon": "mercadopago", "fee": 3.5, "processing_time": "instant", "region": "LATAM"}'),
('pix', 'PIX', 'Бразильская система мгновенных платежей', true, '{"icon": "pix", "fee": 0, "processing_time": "instant", "region": "BR"}'),
('boleto', 'Boleto Bancário', 'Бразильская платежная система', true, '{"icon": "boleto", "fee": 2.0, "processing_time": "1-3 days", "region": "BR"}'),
('oxxo', 'OXXO', 'Мексиканская платежная система', true, '{"icon": "oxxo", "fee": 1.5, "processing_time": "1-2 days", "region": "MX"}'),
('grabpay', 'GrabPay', 'Платежная система Юго-Восточной Азии', true, '{"icon": "grab", "fee": 2.0, "processing_time": "instant", "region": "SEA"}'),
('kakao_pay', 'Kakao Pay', 'Корейская платежная система', true, '{"icon": "kakao", "fee": 2.0, "processing_time": "instant", "region": "KR"}'),
('naver_pay', 'Naver Pay', 'Корейская платежная система Naver', true, '{"icon": "naver", "fee": 2.0, "processing_time": "instant", "region": "KR"}'),
('line_pay', 'LINE Pay', 'Японская платежная система', true, '{"icon": "line", "fee": 2.0, "processing_time": "instant", "region": "JP"}'),
('rakuten_pay', 'Rakuten Pay', 'Японская платежная система Rakuten', true, '{"icon": "rakuten", "fee": 2.5, "processing_time": "instant", "region": "JP"}'),
('paypay', 'PayPay', 'Японская платежная система', true, '{"icon": "paypay", "fee": 1.5, "processing_time": "instant", "region": "JP"}'),

('klarna', 'Klarna', 'Покупка в рассрочку через Klarna', true, '{"icon": "klarna", "fee": 5.0, "processing_time": "instant", "installments": true}'),
('afterpay', 'Afterpay', 'Покупка в рассрочку через Afterpay', true, '{"icon": "afterpay", "fee": 4.0, "processing_time": "instant", "installments": true}'),
('affirm', 'Affirm', 'Покупка в рассрочку через Affirm', true, '{"icon": "affirm", "fee": 5.0, "processing_time": "instant", "installments": true}'),
('sezzle', 'Sezzle', 'Покупка в рассрочку через Sezzle', true, '{"icon": "sezzle", "fee": 4.0, "processing_time": "instant", "installments": true}'),
('splitit', 'Splitit', 'Рассрочка без процентов', true, '{"icon": "splitit", "fee": 3.5, "processing_time": "instant", "installments": true}'),
('tinkoff_installment', 'Рассрочка Tinkoff', 'Рассрочка от Тинькофф', true, '{"icon": "tinkoff", "fee": 4.0, "processing_time": "instant", "installments": true, "region": "RU"}'),
('sberbank_installment', 'Рассрочка Сбербанк', 'Рассрочка от Сбербанка', true, '{"icon": "sberbank", "fee": 4.0, "processing_time": "instant", "installments": true, "region": "RU"}'),

('gift_card', 'Подарочная карта', 'Оплата подарочной картой', true, '{"icon": "gift", "fee": 0, "processing_time": "instant"}'),
('voucher', 'Ваучер', 'Оплата ваучером', true, '{"icon": "ticket", "fee": 0, "processing_time": "instant"}'),
('promo_code', 'Промокод', 'Оплата промокодом', true, '{"icon": "tag", "fee": 0, "processing_time": "instant"}'),
('loyalty_points', 'Бонусные баллы', 'Оплата бонусными баллами', true, '{"icon": "star", "fee": 0, "processing_time": "instant"}'),
('store_credit', 'Кредит магазина', 'Оплата кредитом магазина', true, '{"icon": "wallet", "fee": 0, "processing_time": "instant"}'),

('invoice', 'Счет на оплату', 'Выставление счета для юридических лиц', true, '{"icon": "invoice", "fee": 0, "processing_time": "manual", "b2b": true}'),
('cod', 'Наложенный платеж', 'Оплата при получении (почта)', true, '{"icon": "package", "fee": 3.0, "processing_time": "on_delivery"}'),
('check', 'Чек', 'Оплата чеком', false, '{"icon": "check", "fee": 0, "processing_time": "5-10 days", "deprecated": true}'),
('money_order', 'Денежный перевод', 'Почтовый денежный перевод', false, '{"icon": "mail", "fee": 2.0, "processing_time": "5-10 days", "deprecated": true}'),
('direct_debit', 'Прямое дебетование', 'Автоматическое списание со счета', true, '{"icon": "repeat", "fee": 0.5, "processing_time": "1-3 days", "recurring": true}'),
('ach', 'ACH Transfer', 'Автоматизированная клиринговая палата (США)', true, '{"icon": "bank", "fee": 1.0, "processing_time": "1-3 days", "region": "US"}'),
('e_transfer', 'Interac e-Transfer', 'Канадская система электронных переводов', true, '{"icon": "transfer", "fee": 1.0, "processing_time": "instant", "region": "CA"}'),

('mobile_billing', 'Мобильный платеж', 'Оплата через мобильного оператора', true, '{"icon": "phone", "fee": 15.0, "processing_time": "instant"}'),
('mts_payment', 'МТС Деньги', 'Оплата через МТС', true, '{"icon": "mts", "fee": 10.0, "processing_time": "instant", "region": "RU"}'),
('beeline_payment', 'Beeline', 'Оплата через Beeline', true, '{"icon": "beeline", "fee": 10.0, "processing_time": "instant", "region": "RU"}'),
('megafon_payment', 'MegaFon', 'Оплата через MegaFon', true, '{"icon": "megafon", "fee": 10.0, "processing_time": "instant", "region": "RU"}'),
('tele2_payment', 'Tele2', 'Оплата через Tele2', true, '{"icon": "tele2", "fee": 10.0, "processing_time": "instant", "region": "RU"}'),

('tinkoff_pay', 'Tinkoff Pay', 'Оплата через приложение Тинькофф', true, '{"icon": "tinkoff", "fee": 0, "processing_time": "instant", "region": "RU"}'),
('sberbank_online', 'Сбербанк Онлайн', 'Оплата через Сбербанк Онлайн', true, '{"icon": "sberbank", "fee": 0, "processing_time": "instant", "region": "RU"}'),
('alfa_pay', 'Alfa Pay', 'Оплата через Альфа-Банк', true, '{"icon": "alfabank", "fee": 0, "processing_time": "instant", "region": "RU"}'),
('vtb_pay', 'VTB Pay', 'Оплата через ВТБ', true, '{"icon": "vtb", "fee": 0, "processing_time": "instant", "region": "RU"}'),
('raiffeisen_pay', 'Raiffeisen Pay', 'Оплата через Райффайзенбанк', true, '{"icon": "raiffeisen", "fee": 0, "processing_time": "instant", "region": "RU"}'),

('atm_cash', 'Через банкомат', 'Внесение наличных через банкомат', true, '{"icon": "atm", "fee": 1.0, "processing_time": "instant"}'),
('terminal', 'Терминал оплаты', 'Оплата через платежный терминал', true, '{"icon": "terminal", "fee": 2.0, "processing_time": "instant"}'),
('pos_terminal', 'POS-терминал', 'Оплата через POS-терминал в магазине', true, '{"icon": "pos", "fee": 2.0, "processing_time": "instant"}'),

('barter', 'Бартер', 'Товарообменная сделка', false, '{"icon": "exchange", "fee": 0, "processing_time": "manual", "special": true}'),
('offset', 'Взаимозачет', 'Взаимозачет между компаниями', true, '{"icon": "balance", "fee": 0, "processing_time": "manual", "b2b": true}'),
('escrow', 'Эскроу', 'Оплата через счет эскроу', true, '{"icon": "shield", "fee": 1.0, "processing_time": "manual", "secure": true}'),
('letter_of_credit', 'Аккредитив', 'Оплата через аккредитив', true, '{"icon": "document", "fee": 2.0, "processing_time": "manual", "b2b": true}'),

('nfc_payment', 'NFC платеж', 'Бесконтактная оплата', true, '{"icon": "nfc", "fee": 2.0, "processing_time": "instant", "contactless": true}'),
('qr_payment', 'QR-код оплата', 'Оплата по QR-коду', true, '{"icon": "qr", "fee": 1.0, "processing_time": "instant"}'),
('biometric_payment', 'Биометрия', 'Оплата по биометрии', true, '{"icon": "fingerprint", "fee": 2.0, "processing_time": "instant", "biometric": true}'),
('smart_watch', 'Умные часы', 'Оплата через умные часы', true, '{"icon": "watch", "fee": 2.5, "processing_time": "instant", "wearable": true}'),
('voice_payment', 'Голосовой платеж', 'Оплата голосовым помощником', true, '{"icon": "microphone", "fee": 2.5, "processing_time": "instant", "voice": true}'),
('iot_payment', 'IoT платеж', 'Оплата через IoT устройство', true, '{"icon": "iot", "fee": 2.0, "processing_time": "instant", "iot": true}');