INSERT INTO sales.payment_statuses (code, name, description) VALUES
('pending', 'Pending', 'Payment is awaiting processing'),
('pending_confirmation', 'Pending Confirmation', 'Payment awaiting customer confirmation'),
('processing', 'Processing', 'Payment is being processed by payment gateway'),
('authorized', 'Authorized', 'Payment authorized but not yet captured'),
('captured', 'Captured', 'Payment amount has been captured from authorized transaction'),
('paid', 'Paid', 'Payment successfully completed'),
('completed', 'Completed', 'Payment fully completed and settled'),
('failed', 'Failed', 'Payment attempt failed'),
('declined', 'Declined', 'Payment declined by bank or payment processor'),
('cancelled', 'Cancelled', 'Payment cancelled by customer or system'),
('expired', 'Expired', 'Payment session or authorization expired'),
('refunded', 'Refunded', 'Payment fully refunded to customer'),
('partially_refunded', 'Partially Refunded', 'Payment partially refunded to customer'),
('refund_pending', 'Refund Pending', 'Refund request submitted, awaiting processing'),
('refund_failed', 'Refund Failed', 'Refund attempt failed'),
('chargeback', 'Chargeback', 'Customer initiated chargeback dispute'),
('chargeback_pending', 'Chargeback Pending', 'Chargeback under review'),
('chargeback_won', 'Chargeback Won', 'Merchant won chargeback dispute'),
('chargeback_lost', 'Chargeback Lost', 'Merchant lost chargeback dispute'),
('on_hold', 'On Hold', 'Payment held for review or verification'),
('voided', 'Voided', 'Payment authorization voided before capture'),
('reserved', 'Reserved', 'Payment amount reserved on customer account'),
('settlement', 'Settlement', 'Payment in settlement process with bank'),
('settled', 'Settled', 'Payment settled to merchant account'),
('error', 'Error', 'Payment processing error occurred'),
('timeout', 'Timeout', 'Payment request timed out'),
('insufficient_funds', 'Insufficient Funds', 'Customer has insufficient funds'),
('fraud_suspected', 'Fraud Suspected', 'Payment flagged for potential fraud'),
('fraud_confirmed', 'Fraud Confirmed', 'Payment confirmed as fraudulent'),
('verification_required', 'Verification Required', 'Additional verification required for payment'),
('3ds_pending', '3DS Pending', '3D Secure authentication pending'),
('3ds_failed', '3DS Failed', '3D Secure authentication failed'),
('3ds_success', '3DS Success', '3D Secure authentication successful'),
('bank_transfer_pending', 'Bank Transfer Pending', 'Bank transfer initiated, awaiting completion'),
('cash_on_delivery', 'Cash on Delivery', 'Payment to be collected on delivery'),
('cod_collected', 'COD Collected', 'Cash on delivery payment collected'),
('cod_not_collected', 'COD Not Collected', 'Cash on delivery payment not collected'),
('prepaid', 'Prepaid', 'Order prepaid by customer'),
('credit_hold', 'Credit Hold', 'Payment on credit hold for review'),
('credit_approved', 'Credit Approved', 'Credit payment approved'),
('installment_pending', 'Installment Pending', 'Installment payment plan pending'),
('installment_active', 'Installment Active', 'Installment payment plan active'),
('installment_overdue', 'Installment Overdue', 'Installment payment overdue'),
('installment_completed', 'Installment Completed', 'All installments paid'),
('wallet_pending', 'Wallet Pending', 'Digital wallet payment pending'),
('wallet_paid', 'Wallet Paid', 'Paid via digital wallet'),
('qr_code_pending', 'QR Code Pending', 'QR code payment pending scan'),
('qr_code_scanned', 'QR Code Scanned', 'QR code scanned, awaiting payment'),
('invoice_sent', 'Invoice Sent', 'Invoice sent to customer'),
('invoice_viewed', 'Invoice Viewed', 'Customer viewed invoice'),
('invoice_overdue', 'Invoice Overdue', 'Invoice payment overdue'),
('terminal_pending', 'Terminal Pending', 'POS terminal payment pending'),
('terminal_approved', 'Terminal Approved', 'POS terminal payment approved'),
('terminal_declined', 'Terminal Declined', 'POS terminal payment declined'),
('contactless_pending', 'Contactless Pending', 'Contactless payment pending'),
('contactless_success', 'Contactless Success', 'Contactless payment successful'),
('chip_and_pin', 'Chip and PIN', 'Chip and PIN payment processed'),
('magnetic_stripe', 'Magnetic Stripe', 'Magnetic stripe payment processed'),
('manual_entry', 'Manual Entry', 'Card details manually entered'),
('preauthorized', 'Pre-authorized', 'Payment pre-authorized for future capture'),
('recurring_pending', 'Recurring Pending', 'Recurring payment scheduled'),
('recurring_active', 'Recurring Active', 'Recurring payment active'),
('recurring_failed', 'Recurring Failed', 'Recurring payment failed'),
('recurring_cancelled', 'Recurring Cancelled', 'Recurring payment cancelled'),
('subscription_active', 'Subscription Active', 'Subscription payment active'),
('subscription_paused', 'Subscription Paused', 'Subscription payment paused'),
('subscription_expired', 'Subscription Expired', 'Subscription expired'),
('gift_card_applied', 'Gift Card Applied', 'Gift card payment applied'),
('loyalty_points_applied', 'Loyalty Points Applied', 'Loyalty points used for payment'),
('store_credit_applied', 'Store Credit Applied', 'Store credit applied to payment'),
('partial_payment', 'Partial Payment', 'Partial payment received'),
('overpaid', 'Overpaid', 'Customer paid more than required amount'),
('underpaid', 'Underpaid', 'Customer paid less than required amount'),
('split_payment', 'Split Payment', 'Payment split across multiple methods'),
('pending_review', 'Pending Review', 'Payment under manual review'),
('approved_by_admin', 'Approved by Admin', 'Payment manually approved by administrator'),
('rejected_by_admin', 'Rejected by Admin', 'Payment manually rejected by administrator'),
('reconciliation_pending', 'Reconciliation Pending', 'Payment awaiting reconciliation'),
('reconciled', 'Reconciled', 'Payment reconciled with bank statement'),
('dispute_opened', 'Dispute Opened', 'Payment dispute opened'),
('dispute_resolved', 'Dispute Resolved', 'Payment dispute resolved'),
('anti_fraud_check', 'Anti-Fraud Check', 'Payment undergoing fraud check'),
('kyc_required', 'KYC Required', 'Know Your Customer verification required'),
('aml_check', 'AML Check', 'Anti-Money Laundering check in progress'),
('compliance_hold', 'Compliance Hold', 'Payment held for compliance review'),
('tax_pending', 'Tax Pending', 'Tax calculation pending'),
('customs_hold', 'Customs Hold', 'Payment held for customs clearance'),
('escrow_pending', 'Escrow Pending', 'Payment in escrow awaiting release'),
('escrow_released', 'Escrow Released', 'Escrow payment released'),
('blocked', 'Blocked', 'Payment blocked by system or admin'),
('unblocked', 'Unblocked', 'Previously blocked payment unblocked'),
('archived', 'Archived', 'Payment archived for record keeping'),
('test_payment', 'Test Payment', 'Test transaction for development'),
('sandbox', 'Sandbox', 'Sandbox environment test payment');