INSERT INTO core.roles (role_name, description) VALUES
('customer', 'Regular customer with basic access to catalog and personal account'),
('guest', 'Guest user without registration, limited access'),
('vip_customer', 'VIP customer with extended privileges and personal discounts'),
('wholesale_customer', 'Wholesale client with access to wholesale prices and terms'),
('admin', 'System administrator with full access to all functions'),
('super_admin', 'Super administrator with rights to manage other administrators'),
('store_manager', 'Store manager, managing staff and store operations'),
('regional_manager', 'Regional manager, managing multiple stores in region'),
('cashier', 'Cashier, processing sales and returns on POS terminal'),
('senior_cashier', 'Senior cashier with rights to cancel operations and returns'),
('warehouse_manager', 'Warehouse manager, inventory and logistics management'),
('warehouse_operator', 'Warehouse operator, receiving and shipping goods'),
('inventory_specialist', 'Inventory specialist, stock accounting and control'),
('stocker', 'Stocker, product placement and shelf stock control'),
('merchandiser', 'Merchandiser, planning layout and visual presentation'),
('buyer', 'Buyer, forming supplier orders and assortment management'),
('category_manager', 'Category manager, product category development strategy'),
('pricing_manager', 'Pricing manager, price and promotion management'),
('support', 'Customer support service, consultations and problem solving'),
('support_lead', 'Support team lead'),
('customer_service', 'Customer service specialist, handling customer inquiries'),
('call_center', 'Call center operator, inbound and outbound calls'),
('sales_associate', 'Sales associate, assisting customers on sales floor'),
('sales_rep', 'Sales representative, working with corporate clients'),
('sales_manager', 'Sales manager, managing sales and customer base'),
('delivery_driver', 'Delivery driver, delivering orders to customers'),
('delivery_coordinator', 'Delivery coordinator, route planning and logistics'),
('logistics_manager', 'Logistics manager, supply chain management'),
('accountant', 'Accountant, financial accounting and reporting'),
('financial_controller', 'Financial controller, financial operations control'),
('analyst', 'Data analyst, reports and business analytics'),
('data_analyst', 'Data analyst, working with big data and BI'),
('business_analyst', 'Business analyst, process analysis and optimization'),
('marketing_manager', 'Marketing manager, planning marketing campaigns'),
('marketing_specialist', 'Marketing specialist, implementing marketing activities'),
('smm_manager', 'SMM manager, social media management'),
('content_manager', 'Content manager, website and catalog content management'),
('seo_specialist', 'SEO specialist, search engine optimization'),
('copywriter', 'Copywriter, creating text content'),
('designer', 'Designer, creating visual content'),
('photographer', 'Photographer, product photography'),
('hr_manager', 'HR manager, personnel management and recruiting'),
('hr_specialist', 'HR specialist, personnel records management'),
('recruiter', 'Recruiter, personnel selection'),
('trainer', 'Trainer, staff training and development'),
('security', 'Security, facility security'),
('security_manager', 'Security manager, security service management'),
('loss_prevention', 'Loss prevention specialist'),
('auditor', 'Auditor, conducting internal audits'),
('compliance_officer', 'Compliance officer, regulatory requirements compliance'),
('legal', 'Legal counsel, legal support'),
('it_admin', 'IT administrator, IT infrastructure support'),
('system_admin', 'System administrator, server and system management'),
('network_admin', 'Network administrator, network infrastructure management'),
('developer', 'Developer, software development and maintenance'),
('qa_engineer', 'QA engineer, testing and quality control'),
('devops', 'DevOps engineer, automation and deployment'),
('dba', 'Database administrator, DBMS management'),
('product_manager', 'Product manager, product management'),
('project_manager', 'Project manager, project management'),
('scrum_master', 'Scrum master, agile process facilitation'),
('ceo', 'Chief Executive Officer, company top management'),
('cfo', 'Chief Financial Officer, financial management'),
('coo', 'Chief Operating Officer, operations management'),
('cto', 'Chief Technology Officer, IT and technology management'),
('cmo', 'Chief Marketing Officer, marketing strategy'),
('franchise_owner', 'Franchise owner, managing franchise location'),
('partner', 'Partner, partnership relations with company'),
('supplier', 'Supplier, access to supplier portal'),
('supplier_manager', 'Supplier manager, coordination with retailer'),
('vendor', 'Vendor, manufacturer representative'),
('distributor', 'Distributor, wholesale distribution'),
('mystery_shopper', 'Mystery shopper, service quality inspection'),
('quality_control', 'Quality control, product and service inspection'),
('maintenance', 'Maintenance staff, technical maintenance'),
('cleaner', 'Cleaner, maintaining cleanliness'),
('api_user', 'API user, access via API for integrations'),
('bot', 'Bot, automated process or system'),
('external_auditor', 'External auditor, conducting independent audit'),
('consultant', 'Consultant, external consultant or expert'),
('intern', 'Intern, trainee employee'),
('temp_worker', 'Temporary worker, seasonal or project staff'),
('contractor', 'Contractor, external service provider'),
('readonly', 'Read-only, view-only access without modifications'),
('reports_viewer', 'Reports viewer, access to reports and dashboards'),
('ecommerce_manager', 'E-commerce manager, online sales management'),
('marketplace_manager', 'Marketplace manager, working with trading platforms'),
('loyalty_manager', 'Loyalty program manager, managing bonuses and promotions'),
('crm_manager', 'CRM manager, customer relationship system management'),
('price_monitor', 'Price monitor, competitor price tracking'),
('stock_analyst', 'Stock analyst, inventory optimization'),
('demand_planner', 'Demand planner, sales forecasting'),
('assortment_planner', 'Assortment planner, product matrix formation'),
('visual_merchandiser', 'Visual merchandiser, window and floor display'),
('display_coordinator', 'Display coordinator, product presentation control'),
('returns_specialist', 'Returns specialist, processing returns and complaints'),
('refund_manager', 'Refund manager, returns process management'),
('gift_registry', 'Gift registry, wish list management'),
('personal_shopper', 'Personal shopper, individual product selection'),
('stylist', 'Stylist, style and image consultations'),
('nutritionist', 'Nutritionist, nutrition consultations for grocery stores'),
('pharmacist', 'Pharmacist, medical product consultations'),
('tech_support', 'Technical support, assistance with electronics and gadgets'),
('installer', 'Installer, product installation and mounting'),
('repair_technician', 'Repair technician, service maintenance'),
('service_manager', 'Service center manager');